galaxy_info:
  author: Olivier Pichon <op@united-asian.com>
  description: Install Docker CE
  company: United Asian Management Limited

  license: license (MIT)

  min_ansible_version: 1.2

  platforms:
    - name: Ubuntu
      versions:
        - yakkety
        - trusty
        - xenial

  galaxy_tags:
    - docker

dependencies: []