# Safe-restart Jenkins
- name: Restart Jenkins
  sudo: yes
  command: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 safe-restart

- name: Restart nginx
  service: name=nginx state=restarted