---

- name: Configure Jenkins Port
  sudo: yes
  when: port is defined
  lineinfile: dest=/etc/default/jenkins regexp=^HTTP_PORT= line=HTTP_PORT={{port}}

- name: Configure Jenkins Prefix
  sudo: yes
  when: prefix is defined
  lineinfile: dest=/etc/default/jenkins regexp=^PREFIX= line=PREFIX={{prefix}}

- name: Configure Jenkins Permissions
  template:
    src: jenkins-config.xml
    dest: /var/lib/jenkins/config.xml
    owner: jenkins
    group: jenkins
    mode: 0600
  notify:
    - Restart Jenkins

- name: "Creating folder for slave config"
  file:
    path: "/var/lib/jenkins/jobs/CD_Pipeline"
    state: directory
    mode: 0755
    group: jenkins
    owner: jenkins

- name: Configure Jenkins CD Pipeline for OSRM backend
  template:
    src: jenkins-CD_Pipeline.xml
    dest: /var/lib/jenkins/jobs/CD_Pipeline/config.xml
    owner: jenkins
    group: jenkins
    mode: 0600
  notify:
    - Restart Jenkins

- name: Configure Jenkins E-mail
  sudo: yes
  when: email is defined
  template: src=hudson.tasks.Mailer.xml.j2 dest={{ jenkins_lib }}/hudson.tasks.Mailer.xml owner=jenkins group=jenkins mode=0644

- name: Install nginx
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items: 
    - nginx

- name: Configure nginx
  template:
    src: nginx.default
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart nginx

- lineinfile:
    destfile: /etc/ssh/ssh_config
    line: 'StrictHostKeyChecking no'

- service: name=ssh state=restarted
- service: name=jenkins state=restarted
- service: name=nginx state=restarted
